# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Requirments
        run: |
          apt-get update
          apt-get -y install perl
        
      - name: Change update date
        run: |
            perl -i -p0e 's/<\!-- 更新日期 Start -->\s*\r*\n+.*\r*\n+\s*<\!-- 更新日期 End -->/<\!-- 更新日期 Start -->\n'$(date "+%Y年%m月%d日")'\n<\!-- 更新日期 End -->/' index.md
            perl -i -p0e 's/<\!-- 更新日期 Start -->\s*\r*\n+.*\r*\n+\s*<\!-- 更新日期 End -->/<\!-- 更新日期 Start -->\n'$(date "+%Y年%m月%d日")'\n<\!-- 更新日期 End -->/' README.md
      
      - name: Commit to master
        uses: EndBug/add-and-commit@v9
        with:
          push: origin HEAD:master
          add: "*.md"
          fetch: true
          message: "Bump update date"